In [93]:
import pandas as pd
import numpy as np
import random
from mlxtend.frequent_patterns import apriori, association_rules

In [4]:
df = pd.read_csv('Groceries_dataset.csv')

In [68]:
area_name = ['Mirpur',
             'Mohammadpur','Puran_dhaka','Boshundhora','Uttara', 'Banasree','Tejgaon',
             'Farmgate','Rampura','Badda',
             'Khilkhet','Hazaribagh','Motijheel','Lalbagh','Wari'
            ]

In [73]:
df.head(100)

,Member_number,Date,itemDescription,unitPrice,area,Quantity
0,1808,21-07-2015,tropical fruit,5.51,Uttara,7
1,2552,05-01-2015,whole milk,4.36,Hazaribagh,8
2,2300,19-09-2015,pip fruit,7.75,Mohammadpur,8
3,1187,12-12-2015,other vegetables,3.89,Uttara,4
4,3037,01-02-2015,whole milk,4.16,Banasree,3
...,...,...,...,...,...,...
95,2560,17-05-2015,sausage,4.77,Mirpur,3
96,1503,25-07-2015,chicken,6.12,Lalbagh,5
97,2555,23-12-2015,whole milk,7.84,Mirpur,7
98,3645,12-12-2015,citrus fruit,8.40,Banasree,6
99,3886,11-09-2015,soda,4.80,Badda,4

In [16]:
df.shape

(38765, 3)

In [21]:
df.isna().sum()

Member_number      0
Date               0
itemDescription    0
dtype: int64

<bound method DataFrame.info of        Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]>

In [70]:
df.isna()

       Member_number   Date  itemDescription  unitPrice   area
0              False  False            False      False  False
1              False  False            False      False  False
2              False  False            False      False  False
3              False  False            False      False  False
4              False  False            False      False  False
...              ...    ...              ...        ...    ...
38760          False  False            False      False  False
38761          False  False            False      False  False
38762          False  False            False      False  False
38763          False  False            False      False  False
38764          False  False            False      False  False

[38765 rows x 5 columns]

In [39]:


df['unitPrice'] = [f'{random.uniform(3.5, 10.5):.2f}' for i in range(38765)]

In [63]:
df['unitPrice'] =df['unitPrice'].apply(pd.to_numeric)

In [64]:
df['unitPrice'].dtype

dtype('float64')

In [66]:
df.dtypes

Member_number        int64
Date                object
itemDescription     object
unitPrice          float64
dtype: object

In [69]:
df['area'] = [random.choice(area_name) for i in range(38765)]

In [72]:
df['Quantity'] = [random.randint(3,10) for i in range(38765)]

In [80]:
df['TransactionNo'] = [random.randint(1000,5000) for i in range(38765)]

In [86]:
(df['TransactionNo'] == 4597).sum()

9

In [151]:
all_products = []
for i in range(len(df['itemDescription'])):
    all_products.append(df['itemDescription'][i])

In [222]:
all1 =[] 

st = "whole milk"

st = st+" "+all_products[0] + " " +all_products[1]

for i in range(len(all_products)):
    s = all_products[random.randint(0,10)]+ ' '+ all_products[random.randint(0,10)] +' '+ all_products[random.randint(0,10)]
    all1.append(s)
    

all1[20]

'whole milk pot plants tropical fruit'

In [223]:
len(all_products)

38765

In [205]:
df['itemDescription'] = [all1[i] for i in range(38765)]

In [206]:
df['itemDescription'].isna().sum()

0

In [201]:
df.isna().sum()

Member_number      0
Date               0
itemDescription    0
unitPrice          0
area               0
Quantity           0
TransactionNo      0
dtype: int64

In [225]:
(df['itemDescription'] == 'whole milk tropical fruit').sum()

323

In [224]:
df.head(15)

,Member_number,Date,itemDescription,unitPrice,area,Quantity,TransactionNo
0,1808,21-07-2015,beef misc. beverages,5.51,Uttara,7,4332
1,2552,05-01-2015,pastry rolls/buns,4.36,Hazaribagh,8,4597
2,2300,19-09-2015,beef rolls/buns,7.75,Mohammadpur,8,2991
3,1187,12-12-2015,tropical fruit berries,3.89,Uttara,4,2831
4,3037,01-02-2015,bottled water sausage,4.16,Banasree,3,1645
5,4941,14-02-2015,coffee beef,5.27,Rampura,10,1006
6,4501,08-05-2015,tropical fruit coffee,6.93,Mohammadpur,4,2706
7,3803,23-12-2015,whole milk tropical fruit,9.56,Hazaribagh,3,1447
8,2762,20-03-2015,packaged fruit/vegetables canned beer,9.45,Mohammadpur,10,4031
9,4119,12-02-2015,whole milk whole milk,5.21,Rampura,5,4575
10,1340,24-02-2015,rolls/buns beef,5.72,Mirpur,6,1900
11,2193,14-04-2015,tropical fruit beef,9.99,Badda,10,1351
12,1997,21-07-2015,coffee tropical fruit,6.22,Banasree,10,3774
13,4546,03-09-2015,rolls/buns pastry,9.86,Mirpur,9,3091
14,4736,21-07-2015,other vegetables rolls/buns,7.17,Farmgate,9,4622

In [209]:
df['TransactionNo'] = df['TransactionNo'].astype('str')

In [210]:
df['itemDescription'] = df['itemDescription'].str.strip()

In [226]:
basket_Mirpur = (df[df['area'] =="Mirpur"]
          .groupby(['TransactionNo', 'itemDescription'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('TransactionNo'))

basket_Sweden = (data[data['Country'] =="Sweden"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

# basket_Mohammadpur = (df[df['area'] =="Mohammadpur"]
#           .groupby(['TransactionNo', 'itemDescription'])['Quantity']
#           .sum().unstack().reset_index().fillna(0)
#           .set_index('TransactionNo'))

# basket_Hazaribagh = (df[df['area'] =="Hazaribagh"]
#           .groupby(['TransactionNo', 'itemDescription'])['Quantity']
#           .sum().unstack().reset_index().fillna(0)
#           .set_index('TransactionNo'))

# basket_Uttara = (df[df['area'] =="Uttara"]
#           .groupby(['TransactionNo', 'itemDescription'])['Quantity']
#           .sum().unstack().reset_index().fillna(0)
#           .set_index('TransactionNo'))

# basket_Banasree = (df[df['area'] =="Banasree"]
#           .groupby(['TransactionNo', 'itemDescription'])['Quantity']
#           .sum().unstack().reset_index().fillna(0)
#           .set_index('TransactionNo'))

# basket_Rampura = (df[df['area'] =="Rampura"]
#           .groupby(['TransactionNo', 'itemDescription'])['Quantity']
#           .sum().unstack().reset_index().fillna(0)
#           .set_index('TransactionNo'))

# basket_Farmgate = (df[df['area'] =="Farmgate"]
#           .groupby(['TransactionNo', 'itemDescription'])['Quantity']
#           .sum().unstack().reset_index().fillna(0)
#           .set_index('TransactionNo'))

In [227]:
basket_Mirpur

itemDescription,beef beef,beef berries,beef bottled water,beef brown bread,beef butter,beef butter milk,beef canned beer,beef chicken,beef citrus fruit,beef frankfurter,...,yogurt pastry,yogurt pork,yogurt pot plants,yogurt rolls/buns,yogurt root vegetables,yogurt sausage,yogurt specialty bar,yogurt tropical fruit,yogurt whole milk,yogurt yogurt
TransactionNo,,,,,,,,,,,,,,,,,,,,,
1008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [214]:
# hot encode
def hot_encode(x):
    if(x<= 0):
        return 0
    if(x>= 1):
        return 1

In [228]:
basket_encoded = basket_Mirpur.applymap(hot_encode)
basket_Mirpur = basket_encoded

In [229]:
# basket_Farmgate.head()
basket_Mirpur

itemDescription,beef beef,beef berries,beef bottled water,beef brown bread,beef butter,beef butter milk,beef canned beer,beef chicken,beef citrus fruit,beef frankfurter,...,yogurt pastry,yogurt pork,yogurt pot plants,yogurt rolls/buns,yogurt root vegetables,yogurt sausage,yogurt specialty bar,yogurt tropical fruit,yogurt whole milk,yogurt yogurt
TransactionNo,,,,,,,,,,,,,,,,,,,,,
1008,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1009,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1011,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1012,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1015,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [238]:
frq_items = apriori(basket_Mirpur, min_support = 0.001, use_colnames = True)
 
# Collecting the inferred rules in a dataframe

rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
3,(chocolate butter),(canned beer whole milk),0.001060,0.007423,0.00106,1.000000,134.714286,0.001053,inf
4,(other vegetables fruit/vegetable juice),(tropical fruit whole milk),0.003181,0.011665,0.00106,0.333333,28.575758,0.001023,1.482503
7,(other vegetables pot plants),(other vegetables tropical fruit),0.005302,0.011665,0.00106,0.200000,17.145455,0.000999,1.235419
1,(canned beer root vegetables),(whole milk whole milk),0.005302,0.012195,0.00106,0.200000,16.400000,0.000996,1.234756
2,(canned beer whole milk),(chocolate butter),0.007423,0.001060,0.00106,0.142857,134.714286,0.001053,1.165429

(38765, 3)

In [10]:
data= pd.read_excel('Online_Retail.xlsx')

In [165]:
data.head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom
12,536367,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,8,2010-12-01 08:34:00,3.75,13047.0,United Kingdom
13,536367,22310,IVORY KNITTED MUG COSY,6,2010-12-01 08:34:00,1.65,13047.0,United Kingdom
14,536367,84969,BOX OF 6 ASSORTED COLOUR TEASPOONS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom

In [186]:
data.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [220]:
(data['Description'] == "POPPY'S PLAYHOUSE BEDROOM").sum()

433

In [119]:

# Stripping extra spaces in the description
data['Description'] = data['Description'].str.strip()
 
# Dropping the rows without any invoice number
data.dropna(axis = 0, subset =['InvoiceNo'], inplace = True)
data['InvoiceNo'] = data['InvoiceNo'].astype('str')
 
# Dropping all transactions which were done on credit
data = data[~data['InvoiceNo'].str.contains('C')]

In [120]:
# Transactions done in France
basket_France = (data[data['Country'] =="France"]
		.groupby(['InvoiceNo', 'Description'])['Quantity']
		.sum().unstack().reset_index().fillna(0)
		.set_index('InvoiceNo'))

# Transactions done in the United Kingdom
basket_UK = (data[data['Country'] =="United Kingdom"]
		.groupby(['InvoiceNo', 'Description'])['Quantity']
		.sum().unstack().reset_index().fillna(0)
		.set_index('InvoiceNo'))

# Transactions done in Portugal
basket_Por = (data[data['Country'] =="Portugal"]
		.groupby(['InvoiceNo', 'Description'])['Quantity']
		.sum().unstack().reset_index().fillna(0)
		.set_index('InvoiceNo'))

basket_Sweden = (data[data['Country'] =="Sweden"]
		.groupby(['InvoiceNo', 'Description'])['Quantity']
		.sum().unstack().reset_index().fillna(0)
		.set_index('InvoiceNo'))

In [121]:
basket_France

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581279,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [122]:
basket_encoded = basket_France.applymap(hot_encode)
basket_France = basket_encoded

In [126]:
basket_France

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [128]:
# Building the model
frq_items = apriori(basket_France, min_support = 0.05, use_colnames = True)

# Collecting the inferred rules in a dataframe
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules.head(50)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
44,(JUMBO BAG WOODLAND ANIMALS),(POSTAGE),0.076531,0.765306,0.076531,1.000000,1.306667,0.017961,inf
258,"(RED TOADSTOOL LED NIGHT LIGHT, PLASTERS IN TI...",(POSTAGE),0.051020,0.765306,0.051020,1.000000,1.306667,0.011974,inf
270,"(PLASTERS IN TIN WOODLAND ANIMALS, RED TOADSTO...",(POSTAGE),0.053571,0.765306,0.053571,1.000000,1.306667,0.012573,inf
302,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER PLATES),0.102041,0.127551,0.099490,0.975000,7.644000,0.086474,34.897959
300,"(SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...",(SET/6 RED SPOTTY PAPER CUPS),0.102041,0.137755,0.099490,0.975000,7.077778,0.085433,34.489796
337,"(SET/20 RED RETROSPOT PAPER NAPKINS, POSTAGE, ...",(SET/6 RED SPOTTY PAPER PLATES),0.084184,0.127551,0.081633,0.969697,7.602424,0.070895,28.790816
334,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER CUPS),0.084184,0.137755,0.081633,0.969697,7.039282,0.070036,28.454082
129,(RED RETROSPOT PICNIC BAG),(POSTAGE),0.071429,0.765306,0.068878,0.964286,1.260000,0.014213,6.571429
143,(SET OF 9 BLACK SKULL BALLOONS),(POSTAGE),0.066327,0.765306,0.063776,0.961538,1.256410,0.013015,6.102041
174,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.127551,0.137755,0.122449,0.960000,6.968889,0.104878,21.556122
88,(PACK OF 6 SKULL PAPER CUPS),(POSTAGE),0.063776,0.765306,0.061224,0.960000,1.254400,0.012417,5.867347
134,(RETROSPOT PARTY BAG + STICKER SET),(POSTAGE),0.061224,0.765306,0.058673,0.958333,1.252222,0.011818,5.632653
34,(GUMBALL COAT RACK),(POSTAGE),0.058673,0.765306,0.056122,0.956522,1.249855,0.011219,5.397959
90,(PACK OF 6 SKULL PAPER PLATES),(POSTAGE),0.056122,0.765306,0.053571,0.954545,1.247273,0.010621,5.163265
294,"(SET/6 RED SPOTTY PAPER PLATES, POSTAGE)",(SET/6 RED SPOTTY PAPER CUPS),0.107143,0.137755,0.102041,0.952381,6.913580,0.087281,18.107143
36,(JAM MAKING SET PRINTED),(POSTAGE),0.053571,0.765306,0.051020,0.952381,1.244444,0.010022,4.928571
161,(TEA PARTY BIRTHDAY CARD),(POSTAGE),0.094388,0.765306,0.089286,0.945946,1.236036,0.017050,4.341837
158,(STRAWBERRY LUNCH BOX WITH CUTLERY),(POSTAGE),0.122449,0.765306,0.114796,0.937500,1.225000,0.021085,3.755102
138,(ROUND SNACK BOXES SET OF4 WOODLAND),(POSTAGE),0.158163,0.765306,0.147959,0.935484,1.222366,0.026916,3.637755
24,(CHILDRENS CUTLERY SPACEBOY),(CHILDRENS CUTLERY DOLLY GIRL),0.068878,0.071429,0.063776,0.925926,12.962963,0.058856,12.535714
16,(ASSORTED COLOUR MINI CASES),(POSTAGE),0.068878,0.765306,0.063776,0.925926,1.209877,0.011063,3.168367
140,(SET OF 2 TEA TOWELS APPLE AND PEARS),(POSTAGE),0.068878,0.765306,0.063776,0.925926,1.209877,0.011063,3.168367
204,"(LUNCH BAG APPLE DESIGN, LUNCH BAG RED RETROSPOT)",(POSTAGE),0.066327,0.765306,0.061224,0.923077,1.206154,0.010464,3.051020
234,"(STRAWBERRY LUNCH BOX WITH CUTLERY, LUNCH BOX ...",(POSTAGE),0.063776,0.765306,0.058673,0.920000,1.202133,0.009866,2.933673
277,"(ROUND SNACK BOXES SET OF4 WOODLAND, ROUND SNA...",(POSTAGE),0.063776,0.765306,0.058673,0.920000,1.202133,0.009866,2.933673
13,(ALARM CLOCK BAKELIKE RED),(POSTAGE),0.094388,0.765306,0.086735,0.918919,1.200721,0.014499,2.894558
306,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKEL...",(ALARM CLOCK BAKELIKE RED),0.061224,0.094388,0.056122,0.916667,9.711712,0.050344,10.867347
86,(PACK OF 6 SKULL PAPER PLATES),(PACK OF 6 SKULL PAPER CUPS),0.056122,0.063776,0.051020,0.909091,14.254545,0.047441,10.298469
26,(CIRCUS PARADE CHILDRENS EGG CUP),(POSTAGE),0.056122,0.765306,0.051020,0.909091,1.187879,0.008070,2.581633
96,(PARTY BUNTING),(POSTAGE),0.056122,0.765306,0.051020,0.909091,1.187879,0.008070,2.581633
222,"(LUNCH BAG RED RETROSPOT, LUNCH BAG WOODLAND)",(POSTAGE),0.056122,0.765306,0.051020,0.909091,1.187879,0.008070,2.581633
189,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKEL...",(POSTAGE),0.079082,0.765306,0.071429,0.903226,1.180215,0.010907,2.425170
163,(WOODLAND CHARLOTTE BAG),(POSTAGE),0.073980,0.765306,0.066327,0.896552,1.171494,0.009709,2.268707
196,"(ALARM CLOCK BAKELIKE PINK, ALARM CLOCK BAKELI...",(POSTAGE),0.073980,0.765306,0.066327,0.896552,1.171494,0.009709,2.268707
25,(CHILDRENS CUTLERY DOLLY GIRL),(CHILDRENS CUTLERY SPACEBOY),0.071429,0.068878,0.063776,0.892857,12.962963,0.058856,8.690476
175,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.137755,0.127551,0.122449,0.888889,6.968889,0.104878,7.852041
30,(COFFEE MUG APPLES DESIGN),(POSTAGE),0.068878,0.765306,0.061224,0.888889,1.161481,0.008512,2.112245
20,(CHARLOTTE BAG DOLLY GIRL DESIGN),(POSTAGE),0.066327,0.765306,0.058673,0.884615,1.155897,0.007913,2.034014
39,(JUMBO BAG APPLES),(POSTAGE),0.066327,0.765306,0.058673,0.884615,1.155897,0.007913,2.034014
136,(ROUND SNACK BOXES SET OF 4 FRUITS),(POSTAGE),0.107143,0.765306,0.094388,0.880952,1.151111,0.012391,1.971429
43,(JUMBO BAG SPACEBOY DESIGN),(POSTAGE),0.063776,0.765306,0.056122,0.880000,1.149867,0.007315,1.955782
308,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKEL...",(POSTAGE),0.063776,0.765306,0.056122,0.880000,1.149867,0.007315,1.955782
104,(PLASTERS IN TIN CIRCUS PARADE),(POSTAGE),0.168367,0.765306,0.147959,0.878788,1.148283,0.019107,1.936224
122,(RABBIT NIGHT LIGHT),(POSTAGE),0.188776,0.765306,0.165816,0.878378,1.147748,0.021345,1.929705
10,(ALARM CLOCK BAKELIKE PINK),(POSTAGE),0.102041,0.765306,0.089286,0.875000,1.143333,0.011193,1.877551
94,(PAPER BUNTING RETROSPOT),(POSTAGE),0.081633,0.765306,0.071429,0.875000,1.143333,0.008955,1.877551
130,(RED TOADSTOOL LED NIGHT LIGHT),(POSTAGE),0.181122,0.765306,0.158163,0.873239,1.141033,0.019549,1.851474
296,"(POSTAGE, SET/6 RED SPOTTY PAPER CUPS)",(SET/6 RED SPOTTY PAPER PLATES),0.117347,0.127551,0.102041,0.869565,6.817391,0.087073,6.688776
74,(LUNCH BAG WOODLAND),(POSTAGE),0.117347,0.765306,0.102041,0.869565,1.136232,0.012234,1.799320
6,(ALARM CLOCK BAKELIKE GREEN),(POSTAGE),0.096939,0.765306,0.084184,0.868421,1.134737,0.009996,1.783673